[phases.setup]
nixPkgs = ['apache2', 'php82', 'php82Extensions.mysqli']

[phases.install]
cmds = [
  "mkdir -p /var/log/apache2",
  "mkdir -p /var/run/apache2",
  "a2enmod rewrite",
  "a2enmod php"
]

[start]
cmd = "sed -i \"s|Listen 80|Listen ${PORT}|g\" /etc/apache2/ports.conf && apache2ctl -D FOREGROUND"