[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'nginx']

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx",
  "mkdir -p /var/run",
  "mkdir -p /etc/php-fpm"
]

[start]
cmd = """
cp /app/php-fpm.conf /etc/php-fpm/ && \
cp /app/php.ini /etc/php-fpm/ && \
chmod 777 /var/run && \
sed -i \"s|listen 0.0.0.0:8080|listen 0.0.0.0:$PORT|g\" /app/nginx.conf && \
PHP_INI_SCAN_DIR=/etc/php-fpm PHP_INI_PATH=/etc/php-fpm/php.ini php-fpm --fpm-config /etc/php-fpm/php-fpm.conf & \
nginx -c /app/nginx.conf -g 'daemon off;'
"""