[phases.setup]
nixPkgs = ['nginx']

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx"
]

[start]
cmd = "sed -i \"s|listen \$PORT|listen ${PORT}|g\" /app/nginx.conf && nginx -c /app/nginx.conf -g 'daemon off;'"