[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'nginx']

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx"
]

[start]
cmd = "sed -i \"s|listen 0.0.0.0:8080|listen 0.0.0.0:$PORT|g\" /app/nginx.conf && php-fpm & nginx -c /app/nginx.conf"