[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'nginx']

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx",
  "mkdir -p /var/cache/nginx"
]

[start]
cmd = "php-fpm & nginx -c /app/nginx.conf -g 'daemon off;'"