[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'apache2']

[phases.install]
cmds = [
  "mkdir -p /var/log/apache2",
  "mkdir -p /var/run/apache2"
]

[start]
cmd = "sed -i \"s|Listen 80|Listen $PORT|g\" /etc/apache2/httpd.conf && apache2 -D FOREGROUND"